### PR TITLE
bump go to 1.18 & fix lint errors

### LINKED ISSUE #4: Bump go to 1.18
- [x] Bump go to 1.18
- [x] Fix any lint/compilation errors

### PR DESCRIPTION
**Pull request by tarunKoyalwar**
# Description

- Bump Go version to 1.18
- Fixes lint errors (deprecated etc)

closes #4

### CODE REVIEW

File: cmd/docgen/docgen.go [hunk 1]
```diff
@@ -131,7 +131,7 @@ type Field struct {
 	Tag     string
 	Note    string
 
-	embeddedStruct string
+	// embeddedStruct string
```
Comment (Mzack9999) [inline cmd/docgen/docgen.go:134]: We can remove it if not used

File: cmd/docgen/dstdocgen/dst.go [hunk 2]
```diff
@@ -85,8 +85,8 @@ type Field struct {
 	Tag     string
 	Note    string
 
-	embeddedStruct string
-	EnumFields     []string
+	// embeddedStruct string
```
Comment (Mzack9999) [inline cmd/docgen/dstdocgen/dst.go:88]: same here

File: cmd/docgen/dstdocgen/dst.go [hunk 3]
```diff
@@ -186,9 +186,16 @@ func loadRootPackage() ([]*decorator.Package, error) {
 	if err != nil {
 		return nil, errors.Wrap(err, "could not get absolute path")
 	}
+
+	//  packages.LoadAllSyntax deprecated
```
Comment (Mzack9999) [inline cmd/docgen/dstdocgen/dst.go:190]: please use only one space `// packages....`

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
lgtm - minor changes requested

**Review by Mzack9999 — APPROVED** [review]
